# Generated by Django 5.1.7 on 2026-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bulkinsightrefreshrun'),
        ('integrations', '0005_add_scalability_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='insightsnapshot',
            index=models.Index(fields=['account', '-fetched_at'], name='analytics_i_account_c718ec_idx'),
        ),
        migrations.AddIndex(
            model_name='insightsnapshot',
            index=models.Index(fields=['account', 'platform', '-fetched_at'], name='analytics_i_account_d0c9e8_idx'),
        ),
    ]
