# Generated by Django 5.1.7 on 2026-04-02 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_normalize_legacy_starter_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['subscription_status', 'subscription_expires_on'], name='accounts_us_subscri_9bacca_idx'),
        ),
    ]
