# Generated by Django 5.1.7 on 2026-03-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='integrations.connectedaccount')),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='publishing__status_02b19c_idx'), models.Index(fields=['account', 'scheduled_for'], name='publishing__account_a85e3b_idx')],
            },
        ),
    ]
