# Generated by Django 5.1.7 on 2026-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_add_scalability_indexes'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['status', 'scheduled_for', 'platform'], name='publishing__status_3ad679_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['account', 'status'], name='publishing__account_d5e00b_idx'),
        ),
    ]
