# Generated by Django 5.1.7 on 2026-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
