# Generated by Django 5.1.7 on 2026-04-02 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_add_user_to_connectedaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['user', 'is_active'], name='integration_user_id_51ffe6_idx'),
        ),
    ]
